### ISSUE TITLE
Architectural goals

### ISSUE THREAD

**Issue by nphilou** [giotto-ai/giotto-time#45]
- [x] More 'sklearn'-like API #29 
- [ ] Numpy array support #31 

**Proposal A**
Decorators to convert into DataFrame

**Proposal B**
[array-like](https://scikit-learn.org/stable/glossary.html#term-array-like) transformers (personal preference)

**Issues**
Should we return np.array or pd.DataFrame with np.array as input ?
See https://github.com/scikit-learn/scikit-learn/issues/5523#issuecomment-546240555

Comments and links: 
SL/DataFrame current support: https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html

SL is more likely to (better) support DataFrame in the future: https://scikit-learn.org/dev/roadmap.html
SL sample properties future support: https://github.com/scikit-learn/scikit-learn/issues/4497
SL/Pandas mapping: https://github.com/scikit-learn-contrib/sklearn-pandas (not maintained)

Cesium is not fit_transform compliant: https://github.com/cesium-ml/cesium/issues/243
Prophet don't use np.array at all and isn't sklearn API compliant (but still use fit/transform model). My suggestion would be to have something close to Prophet to allow people using both libs in the same project as smoothly as possible.

Scikit-learn transformers useful links: 
https://scikit-learn.org/dev/developers/develop.html
https://github.com/scikit-learn-contrib/project-template/blob/master/skltemplate/_template.py#L136

To be discussed:

- [x] Transformers name
- [x] Transformers category
- [x] TDA features management #28

**Comment by nphilou** [comment]
- [ ] Refactor causality_tests tests

Modules to make (more) sklearn compatible
- [ ] causality_tests 
- [ ] experimental
- [ ] feature_creation
- [ ] models
